name: "fireshipquotes-production"

services:
  pocketbase:
    image: fq-pocketbase:0.23.12-alpine
    restart: always
    labels:
      project: "fireshipquotes"
      env: "production"
      service: "pocketbase"
    env_file:
      - env/production/.env
    build:
      context: .
      dockerfile: app-pocketbase/Dockerfile.pocketbase
    volumes:
      - ./mnt-production/pocketbase:/pb/pb_data
    
  frontend:
    image: fq-frontend:1.0.0-alpine
    restart: always
    labels:
      project: "fireshipquotes"
      env: "production"
      service: "frontend"
    env_file:
      - env/production/.env
    build:
      context: .
      dockerfile: app-frontend/Dockerfile.frontend
    depends_on:
      - pocketbase

  proxy:
    image: fq-proxy:nginx-1.27.3-alpine
    restart: always
    labels:
      project: "fireshipquotes"
      env: "production"
      service: "proxy"
    env_file:
      - env/production/.env
    build:
      context: .
      dockerfile: app-proxy/Dockerfile.proxy
    ports:
      - "${EXPOSE_PORT}:7733"
    depends_on:
      - pocketbase
      - frontend
      - grafana

  grafana:
    image: fq-grafana-oss:11.4.0-ubuntu
    restart: always
    labels:
      project: "fireshipquotes"
      env: "production"
      service: "grafana"
    env_file:
      - env/production/.env
    build:
      context: .
      dockerfile: app-logging/grafana/Dockerfile.grafana
    volumes:
      - ./mnt-production/grafana:/var/lib/grafana

  loki:
    image: fq-loki:3.3.2
    restart: always
    labels:
      project: "fireshipquotes"
      env: "production"
      service: "loki"
    env_file:
      - env/production/.env
    build:
      context: .
      dockerfile: app-logging/Dockerfile.loki
    volumes:
      - ./mnt-production/loki:/data

  promtail:
    image: fq-promtail:3.3.2
    restart: always
    labels:
      project: "fireshipquotes"
      env: "production"
      service: "promtail"
    env_file:
      - env/production/.env
    build:
      context: .
      dockerfile: app-logging/Dockerfile.promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki

  tarpit:
    image: fq-tarpit:1.1
    restart: always
    labels:
      project: "fireshipquotes"
      env: "production"
      service: "tarpit"
    build:
      context: .
      dockerfile: app-tarpit/Dockerfile.tarpit
    volumes:
      - ./mnt-production/tarpit:/vol/nepenthes
