FROM nginx:1.27.3-bookworm

RUN rm /etc/nginx/conf.d/default.conf

COPY app-proxy/nginx.conf /etc/nginx/nginx.conf
COPY app-proxy/cloudflare-whitelist.conf /etc/nginx/cloudflare-whitelist.conf
COPY app-proxy/templates /etc/nginx/templates
COPY app-proxy/ssl /etc/nginx/ssl
COPY app-proxy/entrypoints/ /docker-entrypoint.d/
RUN chmod -R +x /docker-entrypoint.d/*

EXPOSE 7733